-- SeaPark Database Schema for Supabase

-- Parking spots table
CREATE TABLE parking_spots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    type TEXT CHECK (type IN ('garage', 'street')) NOT NULL,
    price_info JSONB,
    total_spots INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- User reports table
CREATE TABLE user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spot_id BIGINT REFERENCES parking_spots(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    status TEXT CHECK (status IN ('green', 'yellow', 'red')) NOT NULL,
    cleanliness INTEGER CHECK (cleanliness >= 1 AND cleanliness <= 5),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster location queries
CREATE INDEX idx_parking_spots_location ON parking_spots (latitude, longitude);

-- Index for linking reports to spots
CREATE INDEX idx_user_reports_spot_id ON user_reports (spot_id);